/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package proyecto.estructura.pkg2;

import javax.swing.JOptionPane;

/**
 *
 * @author Raul
 */
public class pantalla extends javax.swing.JFrame {

    /**
     * Creates new form pantalla
     */
    public pantalla() {
        initComponents();
        this.txtResultado.setEditable(false);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtNumCiudades = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtCiudadInicial = new javax.swing.JTextField();
        btnCalcular = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        txtNombresCiudades = new javax.swing.JTextArea();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtMatrizDistancias = new javax.swing.JTextArea();
        jScrollPane4 = new javax.swing.JScrollPane();
        txtResultado = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(204, 204, 255));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI Black", 1, 24)); // NOI18N
        jLabel1.setText("Floyd warshall");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 20, 200, 30));

        jLabel2.setText("Ingresa el numero de ciudades:");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 80, -1, -1));

        txtNumCiudades.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNumCiudadesActionPerformed(evt);
            }
        });
        getContentPane().add(txtNumCiudades, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 80, 180, -1));

        jLabel3.setText("Ingrese los nombres de las ciudades:");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 130, -1, -1));

        jLabel4.setText("(Una por linea)");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 150, -1, -1));

        jLabel5.setText("Ingrese la matriz de distancias entre ciudades en kilometros (Ingrese 99999 para vertice sin relacion ):");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 200, -1, -1));

        jLabel6.setText("Ingrese el nombre de la ciudad inicial:");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 310, -1, -1));
        getContentPane().add(txtCiudadInicial, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 310, 170, -1));

        btnCalcular.setText("Calcular ruta optima");
        btnCalcular.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCalcularActionPerformed(evt);
            }
        });
        getContentPane().add(btnCalcular, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 370, -1, -1));

        jButton2.setText("Limpiar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 410, -1, -1));

        jLabel7.setText("Resultado:");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 360, -1, -1));

        txtNombresCiudades.setColumns(20);
        txtNombresCiudades.setRows(5);
        jScrollPane3.setViewportView(txtNombresCiudades);

        getContentPane().add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 130, 210, 60));

        txtMatrizDistancias.setColumns(20);
        txtMatrizDistancias.setRows(5);
        jScrollPane2.setViewportView(txtMatrizDistancias);

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 220, 200, 70));

        txtResultado.setColumns(20);
        txtResultado.setRows(5);
        jScrollPane4.setViewportView(txtResultado);

        getContentPane().add(jScrollPane4, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 350, 290, 80));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtNumCiudadesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNumCiudadesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNumCiudadesActionPerformed

    private void btnCalcularActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCalcularActionPerformed
        try {
        //número de ciudades
        int numCiudades = Integer.parseInt(txtNumCiudades.getText().trim());

        //nombres de las ciudades
        String[] nombresCiudades = txtNombresCiudades.getText().trim().split("\n");

        if (nombresCiudades.length != numCiudades) {
            JOptionPane.showMessageDialog(this, "El número de nombres de ciudades no coincide con la cantidad ingresada.", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }

        //matriz de distancias
        int[][] graph = new int[numCiudades][numCiudades];
        String[] filas = txtMatrizDistancias.getText().trim().split("\n");

        if (filas.length != numCiudades) {
            JOptionPane.showMessageDialog(this, "El número de filas de la matriz de distancias no coincide con la cantidad ingresada.", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }

        for (int i = 0; i < numCiudades; i++) {
            String[] valores = filas[i].trim().split("\\s+");
            if (valores.length != numCiudades) {
                JOptionPane.showMessageDialog(this, "Cada fila de la matriz debe contener " + numCiudades + " valores.", "Error", JOptionPane.ERROR_MESSAGE);
                return;
            }
            for (int j = 0; j < numCiudades; j++) {
                graph[i][j] = valores[j].equalsIgnoreCase("INF") ? 99999 : Integer.parseInt(valores[j]);
            }
        }

        //ciudad inicial
        String ciudadInicialNombre = txtCiudadInicial.getText().trim();
        int ciudadInicial = -1;
        for (int i = 0; i < numCiudades; i++) {
            if (nombresCiudades[i].equalsIgnoreCase(ciudadInicialNombre)) {
                ciudadInicial = i;
                break;
            }
        }

        if (ciudadInicial == -1) {
            JOptionPane.showMessageDialog(this, "Ciudad inicial no encontrada.", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }

        //algoritmo de Floyd-Warshall
        int[][] dist = new int[numCiudades][numCiudades];
        for (int i = 0; i < numCiudades; i++) {
            System.arraycopy(graph[i], 0, dist[i], 0, numCiudades);
        }

        for (int k = 0; k < numCiudades; k++) {
            for (int i = 0; i < numCiudades; i++) {
                for (int j = 0; j < numCiudades; j++) {
                    if (dist[i][k] != 99999 && dist[k][j] != 99999 && dist[i][k] + dist[k][j] < dist[i][j]) {
                        dist[i][j] = dist[i][k] + dist[k][j];
                    }
                }
            }
        }

        //mostrar resultados
        StringBuilder resultado = new StringBuilder("Matriz de distancias más cortas:\n");
        resultado.append("     ");
        for (String ciudad : nombresCiudades) {
            resultado.append(ciudad).append(" ");
        }
        resultado.append("\n");

        for (int i = 0; i < numCiudades; i++) {
            resultado.append(nombresCiudades[i]).append(" ");
            for (int j = 0; j < numCiudades; j++) {
                resultado.append(dist[i][j] == 99999 ? "INF" : dist[i][j]).append(" ");
            }
            resultado.append("\n");
        }

        txtResultado.setText(resultado.toString());

    } catch (NumberFormatException e) {
        JOptionPane.showMessageDialog(this, "Por favor, ingrese datos válidos.", "Error", JOptionPane.ERROR_MESSAGE);
    }

    }//GEN-LAST:event_btnCalcularActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        this.txtCiudadInicial.setText("");
        this.txtNumCiudades.setText("");
        this.txtNombresCiudades.setText("");
        this.txtMatrizDistancias.setText("");
        this.txtResultado.setText("");
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(pantalla.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(pantalla.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(pantalla.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(pantalla.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new pantalla().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCalcular;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTextField txtCiudadInicial;
    private javax.swing.JTextArea txtMatrizDistancias;
    private javax.swing.JTextArea txtNombresCiudades;
    private javax.swing.JTextField txtNumCiudades;
    private javax.swing.JTextArea txtResultado;
    // End of variables declaration//GEN-END:variables
}
